DROP TABLE IF EXISTS vacancies;

CREATE TABLE vacancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(50),
    url VARCHAR(500),
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    city VARCHAR(255),
    salary VARCHAR(100),
    requirements VARCHAR(2000),
    published_at TIMESTAMP,
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vacancies_city ON vacancies(city);
CREATE INDEX IF NOT EXISTS idx_vacancies_company ON vacancies(company);
CREATE INDEX IF NOT EXISTS idx_vacancies_published_at ON vacancies(published_at);
