{
 "title": "p95",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "p95 (fetch time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(jobparser_stage_fetch_time_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (fetch time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jobparser_stage_fetch_time_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 (parse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(jobparser_stage_parse_time_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (parse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(jobparser_stage_parse_time_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 (db)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(jobparser_stage_db_time_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (db)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(jobparser_stage_db_time_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}