{
 "title": "Главная",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (area) (jvm_memory_used_bytes{application=\"vacancy-parser\"}/(1024*1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"vacancy-parser\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU процесса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"vacancy-parser\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95 (HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (rate(http_server_requests_seconds_bucket{application=\"vacancy-parser\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pauses p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (rate(jvm_gc_pause_seconds_bucket{application=\"vacancy-parser\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}